# Wrapper for integrating Stable Diffusion using Hugging Face Diffusers

from diffusers import StableDiffusionPipeline
import torch

def generate_image(prompt):
    """
    Generate an image using Stable Diffusion based on the provided prompt.
    Arguments:
        prompt: Text description for image generation.
    Returns:
        An image object (PIL.Image) generated by Stable Diffusion.
    """
    print("Loading Stable Diffusion model...")
    pipeline = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
    pipeline = pipeline.to("cuda" if torch.cuda.is_available() else "cpu")

    print("Generating the image...")
    image = pipeline(prompt).images[0]  # Get the first generated image
    return image
